export type Locale='de'|'fr';
export type LocalPage={locale:Locale;slug:string;englishId:string;title:string;seoTitle:string;description:string;image:string;imageAlt:string;intro:string;sections:{heading:string;body:string}[];faq:{question:string;answer:string}[];related:string[]};

const de=(slug:string,englishId:string,title:string,seoTitle:string,description:string,image:string,imageAlt:string,intro:string,sections:[string,string][],faq:[string,string][],related:string[]):LocalPage=>({locale:'de',slug,englishId,title,seoTitle,description,image,imageAlt,intro,sections:sections.map(([heading,body])=>({heading,body})),faq:faq.map(([question,answer])=>({question,answer})),related});
const fr=(slug:string,englishId:string,title:string,seoTitle:string,description:string,image:string,imageAlt:string,intro:string,sections:[string,string][],faq:[string,string][],related:string[]):LocalPage=>({locale:'fr',slug,englishId,title,seoTitle,description,image,imageAlt,intro,sections:sections.map(([heading,body])=>({heading,body})),faq:faq.map(([question,answer])=>({question,answer})),related});

export const localePages:LocalPage[]=[
de('dunhuang','places/dunhuang','Dunhuang in China: Reise, Geschichte und Kultur','Dunhuang China – Reiseführer, Geschichte & Mogao-Grotten','Entdecken Sie Dunhuang mit Reiseplanung, Mogao-Grotten, Seidenstraßen-Geschichte, Wüstenlandschaften und fundierten Kulturartikeln.','/images/dunhuang/worlds-mural.jpg','Wandmalerei aus der Kulturwelt von Dunhuang','Dunhuang liegt am Rand der Wüste Gobi im Nordwesten Chinas. Die Oasenstadt verband über Jahrhunderte Handelswege, Religionen, Sprachen und künstlerische Traditionen. Diese deutschsprachige Übersicht verbindet praktische Reiseplanung mit historischem Kontext.',[
['Warum Dunhuang wichtig ist','Die Mogao-Grotten bewahren buddhistische Wandmalereien und Skulpturen aus rund einem Jahrtausend. Die Bibliothekshöhle, heute Höhle 17 genannt, enthielt Zehntausende Manuskripte in mehreren Sprachen. Mingsha-Berg und Mondsichelsee zeigen zugleich die empfindliche Beziehung zwischen Oase und Wüste.'],
['Eine Reise mit Kontext planen','Für einen ersten Besuch sind zwei bis drei volle Tage sinnvoll. Reservieren Sie die Mogao-Grotten zuerst und ordnen Sie Museum, Dünen und westliche Route darum. Öffnungszeiten, Eintritt und Verkehrsverbindungen können sich ändern; prüfen Sie deshalb aktuelle offizielle Angaben.'],
['Deutschsprachiger Einstieg','Beginnen Sie mit dem Dunhuang-Reiseführer, den Mogao-Grotten und der Bibliothekshöhle. Die Artikel trennen dokumentierte Geschichte klar von moderner Deutung und vermeiden unbelegte Heilungs-, Schutz- oder Energieversprechen.']],[['Wofür ist Dunhuang bekannt?','Vor allem für die Mogao-Grotten, die Manuskripte aus Höhle 17, die Lage an den Seidenstraßen sowie Mingsha-Berg und Mondsichelsee.']],['dunhuang-reisefuehrer','mogao-grotten','hoehle-17-bibliothekshoehle','dunhuang-wandmalereien']),
de('dunhuang-reisefuehrer','places/dunhuang/travel-guide','Dunhuang-Reiseführer: Grotten, Wüste und Seidenstraße','Dunhuang Reiseführer 2026 – Route, Grotten & Wüste','Planen Sie Dunhuang mit Mogao-Grotten, Mingsha-Berg, Mondsichelsee, Museum, Reisedauer und einer realistischen Route.','/images/dunhuang/travel-map.png','Illustrierte Karte für eine Dunhuang-Reise','Dunhuang lässt sich am besten als Verbindung von Höhlenkunst, Oasenlandschaft und Grenzgeschichte verstehen. Ein guter Reiseplan gibt jedem Bereich genug Zeit, statt möglichst viele entfernte Ziele an einem Tag abzuhaken.',[
['Die wichtigsten Stationen','Die Mogao-Grotten sind der kulturelle Anker. Mingsha-Berg und Mondsichelsee vermitteln die Landschaft, das Dunhuang-Museum ordnet Epochen und Handelswege ein. Yumen-Pass, Yang-Pass und Yardang benötigen wegen der Entfernungen einen eigenen Ausflug.'],
['Wie viele Tage?','Zwei volle Tage reichen für Mogao, Museum, Dünen und Oase in konzentrierter Form. Drei Tage ermöglichen zusätzlich eine westliche Route. Ankunfts- und Abreisetage sollten nicht automatisch als vollständige Besichtigungstage zählen.'],
['Vor der Buchung','Sichern Sie zuerst den zeitgebundenen Grottenbesuch. Prüfen Sie danach Flug oder Bahn, Unterkunft, Wetter und Transfers. Verlassen Sie sich bei Preisen, Öffnungszeiten und zugänglichen Höhlen nicht auf ältere Reiseblogs.']],[['Sind zwei Tage in Dunhuang genug?','Ja, für Mogao, Stadtmuseum sowie Mingsha-Berg und Mondsichelsee. Für die westliche Route sind drei Tage besser.']],['wie-viele-tage-dunhuang','mogao-grotten','mingsha-berg','mondsichelsee-dunhuang']),
de('wie-viele-tage-dunhuang','places/dunhuang/how-many-days','Wie viele Tage braucht man für Dunhuang?','Wie viele Tage in Dunhuang? 1, 2 oder 3 Tage','Vergleichen Sie ein-, zwei- und dreitägige Dunhuang-Routen für Mogao-Grotten, Wüste, Museum und westliche Seidenstraße.','/images/dunhuang/travel-map.png','Dunhuang-Karte für die Reiseplanung','Planen Sie mindestens zwei volle Tage; drei sind für die erste Reise meist ausgewogener. Die Sehenswürdigkeiten liegen nicht alle nebeneinander, und der Besuch der Mogao-Grotten folgt einem festgelegten Reservierungsablauf.',[
['Ein Tag','Ein Tag ist nur eine Höhepunkte-Route: reservierte Mogao-Grotten plus Mingsha-Berg und Mondsichelsee, sofern Zeit und Wetter passen. Museum und westliche Route fallen normalerweise weg.'],
['Zwei Tage','Mit zwei Tagen lassen sich die Grotten von der Wüstenlandschaft trennen. Ergänzen Sie das Museum, ohne jeden Abschnitt zu hetzen. Diese Variante eignet sich für Reisende mit begrenztem Urlaub.'],
['Drei Tage oder mehr','Am dritten Tag kann eine westliche Route zu Yumen-Pass, Yang-Pass oder Yardang hinzukommen. Ein vierter Tag schafft Puffer für Wetter, längere Museumszeit oder weitere Grottenanlagen.']],[['Kann man Dunhuang an einem Tag sehen?','Man kann zwei Hauptattraktionen besuchen, aber nicht die Region sinnvoll erfassen. Zwei bis drei volle Tage sind deutlich besser.']],['dunhuang-reisefuehrer','mogao-grotten','mingsha-berg','dunhuang-manuskripte']),
de('mogao-grotten','places/dunhuang/mogao-caves','Mogao-Grotten in Dunhuang: Geschichte und Besuch','Mogao-Grotten Dunhuang – Geschichte, Kunst & Besuch','Ein fundierter deutschsprachiger Überblick über Geschichte, Wandmalereien, Skulpturen, Schutz und Besucherregeln der Mogao-Grotten.','/images/dunhuang/mogao-facade.jpg','Felswand der Mogao-Grotten bei Dunhuang','Die UNESCO-geschützten Mogao-Grotten entstanden ab dem 4. Jahrhundert und wurden über viele Dynastien erweitert. Hunderte erhaltene Höhlen verbinden Architektur, Skulptur und Malerei zu einem außergewöhnlichen Archiv buddhistischer Kunst.',[
['Was man sieht','Die zugänglichen Höhlen wechseln aus konservatorischen Gründen. Führungen zeigen Beispiele aus verschiedenen Epochen; eine einzelne Höhle sollte deshalb nicht als garantiert betrachtet werden. Fotografierverbote und begrenzte Aufenthaltszeiten schützen empfindliche Oberflächen.'],
['Historischer Zusammenhang','Stifter, Mönche, lokale Eliten und Herrscherfamilien finanzierten unterschiedliche Programme. Motive zeigen buddhistische Lehren, Paradiesvorstellungen, Jataka-Erzählungen, Stifterbilder und Spuren kulturellen Austauschs.'],
['Besuch vorbereiten','Reservieren Sie über offizielle Kanäle, bringen Sie die verlangte Identifikation mit und planen Sie keinen knappen Anschluss. Lesen Sie vorab über Wandmalereien und Höhle 17; so wird die geführte Zeit verständlicher.']],[['Darf man in den Mogao-Grotten fotografieren?','In den geschützten Höhlen gelten strenge Beschränkungen. Folgen Sie immer den aktuellen Anweisungen vor Ort.']],['dunhuang-wandmalereien','hoehle-17-bibliothekshoehle','dunhuang-manuskripte','dunhuang-reisefuehrer']),
de('mingsha-berg','places/dunhuang/mingsha-mountain','Mingsha-Berg: Singende Sanddünen bei Dunhuang','Mingsha-Berg Dunhuang – Singende Sanddünen','Besuchen Sie Mingsha-Berg und die singenden Dünen mit Landschaftskontext, Zeitplanung und praktischen Hinweisen für Wind und Sonne.','/images/dunhuang/crescent-lake-mingsha.jpg','Mingsha-Dünen rund um den Mondsichelsee','Mingsha Shan wird meist als Singender Sandberg übersetzt. Die Dünen südlich von Dunhuang werden gemeinsam mit dem Mondsichelsee besucht und machen die Lage der Oasenstadt unmittelbar sichtbar.',[
['Warum der Sand singt','Trockene Sandkörner können unter bestimmten Bedingungen summende oder dröhnende Geräusche erzeugen. Feuchtigkeit, Wind und Bewegung beeinflussen das Phänomen; ein hörbarer Klang ist daher kein garantiertes Schauspiel.'],
['Zeit und Belastung','Planen Sie mehrere Stunden. Gehen im Sand kostet Kraft, und Hitze sowie Wind verändern den Besuch. Frühere oder spätere Tageszeiten können angenehmer sein, doch aktuelle Zugangsregeln und Wetterwarnungen haben Vorrang.'],
['Verantwortungsvoll besuchen','Bleiben Sie auf erlaubten Wegen, schützen Sie Wasser und Vegetation und nehmen Sie Abfall mit. Aktivitäten und Kamelritte sind optional; prüfen Sie Anbieter, Sicherheit und Tierwohl.']],[['Sind Mingsha-Berg und Mondsichelsee am selben Ort?','Ja, beide bilden eine zusammenhängende Besucherlandschaft südlich von Dunhuang.']],['mondsichelsee-dunhuang','dunhuang-reisefuehrer','mogao-grotten','wie-viele-tage-dunhuang']),
de('mondsichelsee-dunhuang','places/dunhuang/crescent-lake','Mondsichelsee in Dunhuang: Oase zwischen Dünen','Mondsichelsee Dunhuang – Crescent Lake & Mingsha','Erkunden Sie den Mondsichelsee am Fuß des Mingsha-Bergs und verstehen Sie Oasenlandschaft, Besuchsplanung und Schutz.','/images/dunhuang/crescent-lake-mingsha.jpg','Mondsichelförmiger See zwischen den Dünen von Dunhuang','Der Mondsichelsee, auf Englisch Crescent Lake und auf Chinesisch Yueyaquan, liegt am Fuß der Mingsha-Dünen. Seine Form und der starke Kontrast zwischen Wasser und Sand machten ihn zum bekanntesten Landschaftsmotiv Dunhuangs.',[
['Oase statt Wunderbehauptung','Der See gehört zu einem hydrologisch empfindlichen Oasensystem. Romantische Erzählungen behaupten häufig, er trockne niemals aus; sinnvoller ist es, Wasserstand, Management und Umweltveränderungen als reale Geschichte zu betrachten.'],
['Gemeinsam mit Mingsha planen','Beide Ziele liegen in derselben Besucherzone. Rechnen Sie Zeit für Wege, Aussichtspunkte und wechselndes Wetter ein. Ein Sonnenuntergang kann schön sein, ist aber weder garantiert noch Grund, Sicherheitsregeln zu ignorieren.'],
['Praktische Vorbereitung','Nehmen Sie Wasser, Sonnenschutz, geschlossene Schuhe und Schutz für Elektronik mit. Bei starkem Wind oder Staub folgen Sie lokalen Warnungen und ändern den Plan.']],[['Was bedeutet Yueyaquan?','Der Name bedeutet Mondsichelquelle und bezieht sich auf die charakteristische Form des Sees.']],['mingsha-berg','dunhuang-reisefuehrer','wie-viele-tage-dunhuang','mogao-grotten']),
de('hoehle-17-bibliothekshoehle','places/dunhuang/cave-17','Höhle 17 in Dunhuang: Die Bibliothekshöhle','Dunhuang Höhle 17 – Bibliothekshöhle & Manuskripte','Geschichte der Bibliothekshöhle: Manuskripte, Wiederöffnung durch Wang Yuanlu, Stein und Pelliot sowie digitale Forschung.','/images/dunhuang/symbol-manuscript.jpg','Manuskriptmotiv als Symbol der Bibliothekshöhle','Höhle 17 ist eine kleine Seitenkammer am Korridor von Mogao-Höhle 16. Sie enthielt Zehntausende Handschriften sowie Malereien, Drucke und Textilien, bevor sie im frühen 11. Jahrhundert versiegelt wurde.',[
['Was dort aufbewahrt wurde','Neben buddhistischen Sutras lagen Verträge, Briefe, Kalender, Verwaltungsakten und Texte in mehreren Sprachen. Der moderne Name Bibliothekshöhle bedeutet nicht, dass der Raum wie eine öffentliche Bibliothek organisiert war.'],
['Wiederöffnung und Zerstreuung','Der daoistische Priester Wang Yuanlu öffnete die Kammer 1900. Aurel Stein erwarb 1907 große Bestände, Paul Pelliot 1908 eine weitere Auswahl. Die ungleichen Bedingungen dieser Transaktionen gehören zur modernen Geschichte des Archivs.'],
['Warum wurde sie versiegelt?','Der genaue Grund ist umstritten. Theorien reichen vom Schutz vor politischer Gefahr bis zur respektvollen Lagerung heiliger oder nicht mehr verwendeter Materialien. Eine eindeutige gelöste Geheimnisgeschichte ist nicht belegt.']],[['Was wurde in Höhle 17 gefunden?','Manuskripte, Drucke, Malereien, Textilien und Dokumente religiösen wie alltäglichen Inhalts.']],['dunhuang-manuskripte','diamant-sutra-dunhuang','mogao-grotten','dunhuang-wandmalereien']),
de('dunhuang-manuskripte','places/dunhuang/manuscripts','Dunhuang-Manuskripte: Sprachen, Texte und Alltag','Dunhuang Manuskripte – Höhle 17, Sprachen & Texte','Einführung in die mehrsprachigen Manuskripte aus Höhle 17, ihre Themen, Zerstreuung und digitale Erschließung.','/images/dunhuang/symbol-manuscript.jpg','Manuskriptrollen aus der Welt von Dunhuang','Als Dunhuang-Manuskripte bezeichnet man vor allem die handschriftlichen und gedruckten Texte aus Höhle 17. Sie bewahren nicht nur religiöse Literatur, sondern auch seltene Zeugnisse von Verwaltung, Wirtschaft, Bildung und privatem Leben.',[
['Viele Sprachen','Chinesisch und Tibetisch sind besonders häufig. Hinzu kommen Sanskrit, Khotanesisch, Sogdisch, Altuigurisch und weitere Sprachen oder Schriften. Zweisprachige Stücke zeigen Übersetzung und Kontakt entlang der Seidenstraßen.'],
['Mehr als Sutras','Verträge, Konten, Briefe, Kalender, medizinische Texte und Schulübungen machen das Archiv für Sozialgeschichte wichtig. Ein unscheinbares Dokument kann mehr über Arbeit und Familie verraten als ein berühmtes Kunstwerk.'],
['Digital wieder verbunden','Bestände liegen heute in mehreren Ländern. Das International Dunhuang Programme verknüpft Digitalisate und Katalogdaten, sodass physisch getrennte Fragmente vergleichbar werden.']],[['Kann man Dunhuang-Manuskripte online sehen?','Ja. Das International Dunhuang Programme und beteiligte Bibliotheken stellen viele Bilder und Katalogdaten bereit.']],['hoehle-17-bibliothekshoehle','diamant-sutra-dunhuang','dunhuang-wandmalereien','dunhuang']),
de('diamant-sutra-dunhuang','places/dunhuang/diamond-sutra','Das Dunhuang-Diamant-Sutra von 868','Dunhuang Diamant-Sutra – Ältestes datiertes Druckbuch','Warum die gedruckte Diamant-Sutra-Rolle aus Höhle 17 als ältestes vollständiges datiertes Druckbuch der Welt gilt.','/images/dunhuang/symbol-manuscript.jpg','Manuskriptmotiv für das gedruckte Diamant-Sutra','Das berühmte chinesische Diamant-Sutra ist eine Holzblockdruckrolle aus sieben verbundenen Papierblättern. Ein Kolophon datiert die Herstellung auf den 11. Mai 868 und nennt Wang Jie als Stifter.',[
['Warum das Datum wichtig ist','Druckverfahren existierten bereits früher. Die Rolle ist jedoch vollständig genug und ausdrücklich datiert, weshalb sie als ältestes bekanntes vollständiges datiertes Druckbuch beschrieben wird.'],
['Text und Frontispiz','Eine illustrierte Eingangsszene zeigt den Buddha vor einer Versammlung. Der Mahayana-Text behandelt Weisheit und die Auflösung fester Vorstellungen; er ist mehr als ein Meilenstein der Drucktechnik.'],
['Von Dunhuang nach London','Aurel Stein erwarb die Rolle 1907 von Wang Yuanlu. Sie befindet sich heute in der British Library und kann digital untersucht werden. Die Machtverhältnisse der damaligen Erwerbung bleiben Teil ihrer Geschichte.']],[['Wo wurde das Diamant-Sutra gefunden?','In Höhle 17, der Bibliothekshöhle der Mogao-Grotten bei Dunhuang.']],['hoehle-17-bibliothekshoehle','dunhuang-manuskripte','mogao-grotten','dunhuang']),
de('dunhuang-wandmalereien','places/dunhuang/murals','Dunhuang-Wandmalereien: Kunst der Mogao-Grotten','Dunhuang Wandmalereien – Motive, Geschichte & Mogao','Entdecken Sie Themen, Epochen und kulturellen Austausch in den Wandmalereien der Mogao-Grotten.','/images/dunhuang/dunhuang-buddhist-mural.webp','Buddhistische Wandmalerei aus Dunhuang','Die Wandmalereien von Dunhuang entstanden über viele Jahrhunderte. Sie verbinden buddhistische Lehre, Erzählung, Stiftergedächtnis, Architekturvorstellung und Spuren des Austauschs zwischen China, Zentralasien und weiteren Regionen.',[
['Welche Motive erscheinen','Zu sehen sind Buddhas und Bodhisattvas, Paradiesdarstellungen, Jataka-Erzählungen, musizierende Feitian, Stifterporträts und Szenen des Alltags. Motive verändern sich nach Epoche und Auftraggeber.'],
['Farbe und Erhaltung','Mineralpigmente, Bindemittel, Untergrund, Licht und spätere Veränderungen bestimmen das heutige Erscheinungsbild. Heutige Farben dürfen nicht automatisch als ursprüngliche symbolische Codes gelesen werden.'],
['Wie man sie betrachtet','Achten Sie auf die Beziehung zwischen Malerei, Skulptur und Raum. Fotografiereinschränkungen und kurze Führungszeiten dienen dem Schutz; digitale Rekonstruktionen ermöglichen längere vergleichende Betrachtung.']],[['Wie alt sind die Dunhuang-Wandmalereien?','Die Mogao-Kunst reicht über ungefähr ein Jahrtausend, vom 4. bis zum 14. Jahrhundert.']],['mogao-grotten','dunhuang-feitian','neunfarbiger-hirsch','dunhuang']),
de('dunhuang-feitian','places/dunhuang/feitian','Dunhuang Feitian: Fliegende Figuren der Mogao-Grotten','Dunhuang Feitian – Fliegende Apsaras in Mogao','Was Feitian in Dunhuang darstellen, wie sie sich bewegen und warum sie nicht als westliche Engel missverstanden werden sollten.','/images/dunhuang/symbol-feitian.jpg','Fliegende Feitian-Figur aus der Bildwelt Dunhuangs','Feitian sind himmlische, häufig musizierende Figuren in der buddhistischen Kunst Dunhuangs. Sie schweben durch wehende Bänder, Körperhaltung und Komposition, meist ohne die Vogelflügel westlicher Engel.',[
['Kulturelle Herkunft','Die Bildidee entwickelte sich aus indischen und zentralasiatischen Traditionen und wurde in China neu gestaltet. Übersetzungen wie fliegende Apsara sind hilfreich, decken aber nicht jede Figur oder Funktion vollständig ab.'],
['Musik und Bewegung','Instrumente, flatternde Stoffe und geschwungene Linien verwandeln eine feste Wand in vorgestellte Bewegung. Unterschiede zwischen Höhlen zeigen, wie Stile über Jahrhunderte wechselten.'],
['Moderne Verwendung','Feitian inspirieren Tanz, Schmuck und Design. Verantwortungsvolle Nutzung nennt die buddhistische und kunsthistorische Herkunft, statt eine angeblich uralte Garantie für Freiheit, Glück oder Heilung zu erfinden.']],[['Sind Feitian Engel?','Nein. Der Vergleich erklärt nur das Fliegen; Feitian gehören zu buddhistischen und asiatischen Bildtraditionen.']],['dunhuang-wandmalereien','mogao-grotten','neunfarbiger-hirsch','dunhuang']),
de('neunfarbiger-hirsch','places/dunhuang/nine-colored-deer-meaning','Der neunfarbige Hirsch von Dunhuang','Neunfarbiger Hirsch – Dunhuang Höhle 257 Geschichte','Die Jataka-Erzählung des neunfarbigen Hirsches in Mogao-Höhle 257: Rettung, Verrat, Mitgefühl und verantwortungsvolle Deutung.','/images/dunhuang/nine-colored-deer.jpg','Neunfarbiger Hirsch aus einer Dunhuang-Wandmalerei','Die Wandmalerei in Mogao-Höhle 257 erzählt eine Jataka-Geschichte über einen außergewöhnlichen Hirsch, der einen Ertrinkenden rettet. Der Gerettete verrät später den Aufenthaltsort des Hirsches aus Gier nach Belohnung.',[
['Die Erzählung','Der Hirsch verlangt lediglich, dass sein Versteck geheim bleibt. Als der Mann das Versprechen bricht, erklärt der Hirsch vor dem Herrscher die Rettung und den Verrat. Der Herrscher erkennt die moralische Schuld und schützt das Tier.'],
['Was sie bedeutet','Die Geschichte wird mit Mitgefühl, Dankbarkeit, Wahrhaftigkeit und den Grenzen selbstloser Hilfe verbunden. Als Jataka verweist sie auf eine frühere Existenz des Buddha und ethische Vervollkommnung.'],
['Moderne Symbole','Ein Hirschmotiv kann heute an Integrität erinnern. Es ist jedoch keine historisch belegte Schutz- oder Heilungsgarantie. Gute Gestaltung nennt Höhle 257 und die Erzählung, statt nur ein dekoratives Tier zu übernehmen.']],[['Wo befindet sich die Malerei des neunfarbigen Hirsches?','In Mogao-Höhle 257 bei Dunhuang. Der Zugang zu bestimmten Höhlen hängt vom aktuellen Besuchsprogramm ab.']],['dunhuang-wandmalereien','dunhuang-feitian','mogao-grotten','dunhuang']),

fr('dunhuang','places/dunhuang','Dunhuang en Chine : voyage, histoire et culture','Dunhuang Chine – Guide, histoire & grottes de Mogao','Découvrez Dunhuang grâce à des guides de voyage, aux grottes de Mogao, à l’histoire des routes de la soie et à des articles culturels documentés.','/images/dunhuang/worlds-mural.jpg','Peinture murale appartenant au monde culturel de Dunhuang','Dunhuang se trouve aux marges du désert de Gobi, dans le nord-ouest de la Chine. Pendant des siècles, cette ville-oasis a relié routes commerciales, religions, langues et traditions artistiques. Cette introduction française associe préparation pratique et contexte historique.',[
['Pourquoi Dunhuang est essentiel','Les grottes de Mogao conservent près d’un millénaire de peintures et de sculptures bouddhiques. La grotte 17 contenait des dizaines de milliers de manuscrits en plusieurs langues. Le mont Mingsha et le lac du Croissant révèlent la relation fragile entre oasis et désert.'],
['Préparer un voyage contextualisé','Deux à trois journées complètes conviennent à une première visite. Réservez d’abord Mogao, puis organisez musée, dunes et route occidentale autour de cet horaire. Vérifiez toujours les informations officielles récentes.'],
['Commencer en français','Lisez le guide de voyage, l’introduction aux grottes de Mogao et le dossier sur la grotte-bibliothèque. Les textes distinguent les faits documentés des interprétations modernes et évitent les promesses énergétiques ou thérapeutiques non fondées.']],[['Pourquoi Dunhuang est-il célèbre ?','Pour les grottes de Mogao, les manuscrits de la grotte 17, les routes de la soie, le mont Mingsha et le lac du Croissant.']],['guide-voyage-dunhuang','grottes-de-mogao','grotte-17-bibliotheque','peintures-murales-dunhuang']),
fr('guide-voyage-dunhuang','places/dunhuang/travel-guide','Guide de voyage à Dunhuang : grottes, désert et soie','Guide Dunhuang 2026 – Itinéraire, Mogao & désert','Organisez Dunhuang avec les grottes de Mogao, Mingsha, le lac du Croissant, le musée, la durée du séjour et une route réaliste.','/images/dunhuang/travel-map.png','Carte illustrée pour préparer un voyage à Dunhuang','Dunhuang se comprend comme la rencontre de l’art rupestre, de l’oasis et de l’histoire frontalière. Un bon itinéraire accorde du temps à chaque univers au lieu d’accumuler des sites éloignés.',[
['Les étapes essentielles','Mogao constitue l’ancrage culturel. Mingsha et le lac du Croissant montrent le paysage, tandis que le musée replace les périodes et les routes. Yumen, Yangguan et Yardang demandent une excursion distincte.'],
['Combien de jours ?','Deux jours complets couvrent Mogao, le musée, les dunes et l’oasis. Trois jours permettent d’ajouter la route occidentale. Ne comptez pas automatiquement les jours d’arrivée et de départ comme des journées entières.'],
['Avant de réserver','Fixez d’abord la visite minutée de Mogao. Vérifiez ensuite avion ou train, hébergement, météo et transferts. Pour les prix, horaires et grottes ouvertes, une source officielle récente prime sur un ancien blog.']],[['Deux jours suffisent-ils à Dunhuang ?','Oui pour Mogao, le musée, Mingsha et le lac du Croissant. Trois jours sont préférables pour la route occidentale.']],['combien-de-jours-dunhuang','grottes-de-mogao','mont-mingsha','lac-croissant-dunhuang']),
fr('combien-de-jours-dunhuang','places/dunhuang/how-many-days','Combien de jours faut-il pour visiter Dunhuang ?','Combien de jours à Dunhuang ? 1, 2 ou 3 jours','Comparez les itinéraires d’un, deux et trois jours pour Mogao, le désert, le musée et la route occidentale.','/images/dunhuang/travel-map.png','Carte de Dunhuang pour planifier la durée du séjour','Prévoyez au moins deux journées complètes ; trois offrent généralement un meilleur équilibre. Les sites sont dispersés et la visite des grottes de Mogao dépend d’une réservation précise.',[
['Une journée','Une seule journée permet uniquement les incontournables : Mogao réservé puis Mingsha et le lac du Croissant si les horaires et la météo le permettent. Le musée et l’ouest sont normalement exclus.'],
['Deux journées','Séparez les grottes du paysage désertique et ajoutez le musée. Cette formule convient aux voyageurs pressés tout en évitant de transformer Mogao en arrêt photographique.'],
['Trois jours ou davantage','Le troisième jour accueille Yumen, Yangguan ou Yardang. Un quatrième crée une marge météo, du temps au musée ou une excursion vers une autre série de grottes.']],[['Peut-on visiter Dunhuang en une journée ?','On peut voir deux sites majeurs, mais pas comprendre la région. Deux ou trois jours sont nettement préférables.']],['guide-voyage-dunhuang','grottes-de-mogao','mont-mingsha','manuscrits-dunhuang']),
fr('grottes-de-mogao','places/dunhuang/mogao-caves','Grottes de Mogao à Dunhuang : histoire et visite','Grottes de Mogao Dunhuang – Histoire, art & visite','Présentation documentée de l’histoire, des peintures, des sculptures, de la conservation et des règles de visite des grottes de Mogao.','/images/dunhuang/mogao-facade.jpg','Façade rocheuse des grottes de Mogao près de Dunhuang','Classées par l’UNESCO, les grottes de Mogao furent aménagées à partir du IVe siècle et enrichies sous de nombreuses dynasties. Des centaines de grottes associent architecture, sculpture et peinture dans une archive exceptionnelle de l’art bouddhique.',[
['Ce que l’on visite','Les grottes accessibles changent pour des raisons de conservation. Les circuits montrent plusieurs périodes ; aucune grotte numérotée ne doit être considérée comme garantie. Les limites de temps et de photographie protègent les surfaces fragiles.'],
['Contexte historique','Donateurs, moines, élites locales et familles dirigeantes financèrent des programmes différents. Les images présentent enseignements bouddhiques, paradis, récits jataka, portraits de donateurs et échanges culturels.'],
['Bien se préparer','Réservez par les canaux officiels, apportez l’identification demandée et évitez une correspondance trop serrée. Une lecture préalable sur les peintures et la grotte 17 enrichit fortement la visite guidée.']],[['Peut-on photographier dans les grottes ?','Les espaces protégés appliquent des restrictions strictes. Suivez les consignes actuelles sur place.']],['peintures-murales-dunhuang','grotte-17-bibliotheque','manuscrits-dunhuang','guide-voyage-dunhuang']),
fr('mont-mingsha','places/dunhuang/mingsha-mountain','Mont Mingsha : les dunes chantantes de Dunhuang','Mont Mingsha Dunhuang – Dunes chantantes','Visitez les dunes chantantes avec leur contexte naturel, le choix du moment et des conseils adaptés au soleil et au vent.','/images/dunhuang/crescent-lake-mingsha.jpg','Dunes de Mingsha autour du lac du Croissant','Mingsha Shan est généralement traduit par montagne du sable chantant. Les dunes au sud de Dunhuang se visitent avec le lac du Croissant et rendent immédiatement visible la situation de la ville-oasis.',[
['Pourquoi le sable chante','Des grains secs peuvent produire un grondement ou un bourdonnement dans certaines conditions. Humidité, vent et mouvement modifient le phénomène : le son n’est jamais un spectacle garanti.'],
['Temps et effort','Prévoyez plusieurs heures. Marcher dans le sable fatigue, tandis que chaleur et vent transforment l’expérience. Les heures plus fraîches peuvent être agréables, mais les alertes et règles d’accès restent prioritaires.'],
['Visiter avec respect','Restez sur les parcours autorisés, protégez l’eau et la végétation et remportez vos déchets. Les activités et promenades à dos de chameau sont facultatives ; vérifiez sécurité et bien-être animal.']],[['Mingsha et le lac du Croissant sont-ils au même endroit ?','Oui, ils forment un même paysage touristique au sud de Dunhuang.']],['lac-croissant-dunhuang','guide-voyage-dunhuang','grottes-de-mogao','combien-de-jours-dunhuang']),
fr('lac-croissant-dunhuang','places/dunhuang/crescent-lake','Lac du Croissant à Dunhuang : une oasis dans les dunes','Lac du Croissant Dunhuang – Yueyaquan & Mingsha','Découvrez le lac du Croissant au pied de Mingsha, son paysage d’oasis, la préparation de la visite et sa protection.','/images/dunhuang/crescent-lake-mingsha.jpg','Lac en forme de croissant parmi les dunes de Dunhuang','Le lac du Croissant, appelé Yueyaquan en chinois, se situe au pied des dunes de Mingsha. Sa forme et le contraste entre eau et sable en ont fait l’image paysagère la plus connue de Dunhuang.',[
['Une oasis, pas un miracle','Le lac appartient à un système hydrologique fragile. Les récits affirmant qu’il ne sèche jamais simplifient la réalité ; niveau d’eau, gestion et changements environnementaux font partie de son histoire.'],
['Organiser Mingsha et le lac','Les deux sites partagent la même zone de visite. Gardez du temps pour les déplacements, les points de vue et la météo. Un coucher de soleil n’est ni garanti ni une raison d’ignorer les règles.'],
['Préparation pratique','Emportez eau, protection solaire, chaussures fermées et protection pour les appareils. En cas de vent fort ou de poussière, suivez les alertes locales et changez de programme.']],[['Que signifie Yueyaquan ?','Le nom signifie source en croissant de lune et décrit la forme du lac.']],['mont-mingsha','guide-voyage-dunhuang','combien-de-jours-dunhuang','grottes-de-mogao']),
fr('grotte-17-bibliotheque','places/dunhuang/cave-17','Grotte 17 de Dunhuang : la grotte-bibliothèque','Dunhuang Grotte 17 – Bibliothèque & manuscrits','Histoire de la grotte-bibliothèque, des manuscrits, de Wang Yuanlu, de Stein et Pelliot, puis de la recherche numérique.','/images/dunhuang/symbol-manuscript.jpg','Manuscrit symbolisant la grotte-bibliothèque','La grotte 17 est une petite chambre latérale reliée au corridor de la grotte 16 de Mogao. Avant sa fermeture au début du XIe siècle, elle reçut des dizaines de milliers de manuscrits, peintures, estampes et textiles.',[
['Ce qu’elle contenait','À côté des sutras bouddhiques se trouvaient contrats, lettres, calendriers, archives et textes multilingues. Le nom moderne de bibliothèque ne signifie pas que la pièce fonctionnait comme une salle de lecture publique.'],
['Ouverture et dispersion','Le prêtre taoïste Wang Yuanlu rouvrit la chambre en 1900. Aurel Stein acquit un grand ensemble en 1907, puis Paul Pelliot fit une autre sélection en 1908. Les conditions inégales de ces transactions restent essentielles.'],
['Pourquoi fut-elle fermée ?','La raison exacte demeure discutée : protection face à une menace politique ou dépôt respectueux de matériaux sacrés devenus inutilisés. Aucun récit de mystère définitivement résolu n’est établi.']],[['Que trouva-t-on dans la grotte 17 ?','Des manuscrits, imprimés, peintures, textiles et documents religieux comme quotidiens.']],['manuscrits-dunhuang','sutra-diamant-dunhuang','grottes-de-mogao','peintures-murales-dunhuang']),
fr('manuscrits-dunhuang','places/dunhuang/manuscripts','Manuscrits de Dunhuang : langues, textes et vies','Manuscrits Dunhuang – Grotte 17, langues & textes','Introduction aux manuscrits multilingues de la grotte 17, à leurs sujets, leur dispersion et leur étude numérique.','/images/dunhuang/symbol-manuscript.jpg','Rouleaux manuscrits du monde de Dunhuang','Les manuscrits de Dunhuang désignent surtout les textes écrits ou imprimés provenant de la grotte 17. Ils conservent littérature religieuse, mais aussi des témoignages rares sur l’administration, l’économie, l’éducation et la vie privée.',[
['De nombreuses langues','Le chinois et le tibétain dominent, avec le sanskrit, le khotanais, le sogdien, le vieux ouïghour et d’autres écritures. Certains objets bilingues témoignent de traduction et de contacts.'],
['Bien plus que des sutras','Contrats, comptes, lettres, calendriers, médecine et exercices scolaires rendent l’archive essentielle à l’histoire sociale. Un document modeste peut révéler davantage sur le travail qu’une peinture célèbre.'],
['Une réunion numérique','Les collections sont aujourd’hui réparties entre plusieurs pays. L’International Dunhuang Programme relie images et catalogues afin de comparer des fragments physiquement séparés.']],[['Peut-on voir les manuscrits en ligne ?','Oui. L’International Dunhuang Programme et les institutions partenaires publient de nombreux documents numérisés.']],['grotte-17-bibliotheque','sutra-diamant-dunhuang','peintures-murales-dunhuang','dunhuang']),
fr('sutra-diamant-dunhuang','places/dunhuang/diamond-sutra','Le Sūtra du Diamant de Dunhuang, daté de 868','Sūtra du Diamant Dunhuang – Livre imprimé de 868','Pourquoi le rouleau imprimé découvert dans la grotte 17 est considéré comme le plus ancien livre imprimé complet et daté.','/images/dunhuang/symbol-manuscript.jpg','Manuscrit évoquant le Sūtra du Diamant imprimé','Le célèbre Sūtra du Diamant chinois est un rouleau xylographié composé de sept feuilles assemblées. Son colophon donne la date du 11 mai 868 et nomme Wang Jie comme commanditaire.',[
['Pourquoi cette date compte','L’impression existait auparavant. Mais ce rouleau est suffisamment complet et explicitement daté, d’où sa description comme plus ancien livre imprimé complet et daté connu.'],
['Texte et frontispice','Une scène illustrée montre le Bouddha enseignant devant une assemblée. Ce texte mahayana traite de sagesse et de l’abandon des concepts figés ; il dépasse l’histoire technique de l’imprimerie.'],
['De Dunhuang à Londres','Aurel Stein acquit le rouleau auprès de Wang Yuanlu en 1907. Conservé à la British Library, il est consultable en ligne. Les rapports de pouvoir de l’acquisition restent partie intégrante de son histoire.']],[['Où le Sūtra du Diamant fut-il trouvé ?','Dans la grotte 17, la grotte-bibliothèque des grottes de Mogao près de Dunhuang.']],['grotte-17-bibliotheque','manuscrits-dunhuang','grottes-de-mogao','dunhuang']),
fr('peintures-murales-dunhuang','places/dunhuang/murals','Peintures murales de Dunhuang : l’art de Mogao','Peintures de Dunhuang – Motifs, histoire & Mogao','Explorez les sujets, les périodes et les échanges culturels des peintures murales des grottes de Mogao.','/images/dunhuang/dunhuang-buddhist-mural.webp','Peinture murale bouddhique de Dunhuang','Les peintures de Dunhuang furent réalisées pendant de nombreux siècles. Elles associent enseignement bouddhique, narration, mémoire des donateurs, architecture imaginée et traces d’échanges entre Chine et Asie centrale.',[
['Quels motifs ?','Bouddhas, bodhisattvas, paradis, récits jataka, Feitian musiciens, portraits de donateurs et scènes quotidiennes apparaissent. Les styles et fonctions changent selon époque et commanditaire.'],
['Couleur et conservation','Pigments minéraux, liants, support, lumière et altérations déterminent l’aspect actuel. Les couleurs visibles ne doivent pas être transformées automatiquement en codes spirituels originels.'],
['Comment regarder','Observez les rapports entre peinture, sculpture et espace. Les limites de photographie protègent les grottes ; les reconstructions numériques permettent une comparaison plus longue.']],[['Quel âge ont les peintures de Dunhuang ?','L’art de Mogao couvre environ un millénaire, du IVe au XIVe siècle.']],['grottes-de-mogao','feitian-dunhuang','cerf-neuf-couleurs','dunhuang']),
fr('feitian-dunhuang','places/dunhuang/feitian','Feitian de Dunhuang : figures volantes de Mogao','Dunhuang Feitian – Apsaras volantes des grottes de Mogao','Comprendre les Feitian, leur mouvement, leur musique et pourquoi elles ne sont pas simplement des anges occidentaux.','/images/dunhuang/symbol-feitian.jpg','Figure Feitian volante de Dunhuang','Les Feitian sont des figures célestes, souvent musiciennes, dans l’art bouddhique de Dunhuang. Rubans, posture et composition les font voler sans les ailes d’oiseau des anges occidentaux.',[
['Origines culturelles','Le modèle visuel se développe à partir de traditions indiennes et centrasiatiques, puis se transforme en Chine. La traduction apsara volante aide, mais ne couvre pas toutes les figures.'],
['Musique et mouvement','Instruments, étoffes flottantes et lignes courbes donnent du mouvement à la paroi fixe. Les différences entre grottes montrent l’évolution des styles sur plusieurs siècles.'],
['Usages modernes','Les Feitian inspirent danse, bijoux et design. Une utilisation responsable cite l’origine bouddhique et artistique, sans inventer une ancienne promesse de liberté, de chance ou de guérison.']],[['Les Feitian sont-elles des anges ?','Non. La comparaison explique seulement le vol ; elles appartiennent aux traditions bouddhiques et asiatiques.']],['peintures-murales-dunhuang','grottes-de-mogao','cerf-neuf-couleurs','dunhuang']),
fr('cerf-neuf-couleurs','places/dunhuang/nine-colored-deer-meaning','Le cerf aux neuf couleurs de Dunhuang','Cerf aux neuf couleurs – Récit de la grotte 257','Le récit jataka peint dans la grotte 257 : sauvetage, trahison, compassion et interprétation responsable.','/images/dunhuang/nine-colored-deer.jpg','Cerf aux neuf couleurs dans une peinture de Dunhuang','La peinture de la grotte 257 raconte un jataka consacré à un cerf extraordinaire qui sauve un homme de la noyade. L’homme révèle ensuite sa cachette dans l’espoir d’obtenir une récompense.',[
['Le récit','Le cerf demande seulement que son refuge reste secret. Lorsque la promesse est brisée, il expose devant le souverain le sauvetage et la trahison. Le souverain reconnaît la faute et protège l’animal.'],
['Signification','L’histoire concerne compassion, gratitude, vérité et limites de l’aide désintéressée. Comme jataka, elle renvoie à une vie antérieure du Bouddha et au perfectionnement éthique.'],
['Symbole contemporain','Le motif peut rappeler l’intégrité, mais il n’offre aucune garantie historique de protection ou de guérison. Un bon design cite la grotte 257 et son récit.']],[['Où se trouve la peinture du cerf ?','Dans la grotte 257 de Mogao. L’accès dépend du programme de visite actuel.']],['peintures-murales-dunhuang','feitian-dunhuang','grottes-de-mogao','dunhuang']),

de('yang-pass','places/dunhuang/yang-pass','Yang-Pass bei Dunhuang: Geschichte und Besuch','Yang-Pass Dunhuang – Yangguan Geschichte & Anreise','Geschichte, Ruinenlandschaft und praktische Planung für Yangguan, den südlichen Han-Pass westlich von Dunhuang.','/images/dunhuang/yang-pass.jpg','Wüstenlandschaft am Yang-Pass westlich von Dunhuang','Der Yang-Pass, chinesisch Yangguan, entstand in der Han-Zeit als südlicher Kontrollpunkt der Wege von Dunhuang nach Westen. Heute verbindet der Besuch archäologische Spuren, eine rekonstruierte Vermittlungslandschaft und den Blick über einen Korridor, den Gesandte, Händler und Soldaten durchquerten.',[
['Historische Funktion','Yangguan war kein einzelnes romantisches Tor, sondern Teil eines Grenzsystems aus Pass, Signalstationen, Befestigungen und Routen. Schriftquellen und archäologische Funde helfen, Verwaltung und Bewegung zu verstehen; moderne Rekonstruktionen müssen von originalem Bestand unterschieden werden.'],
['Was Besucher erwartet','Die weite Wüstenlandschaft vermittelt Entfernung und Sichtachsen besser als ein kurzer Fotostopp. Ausstellungstexte, Aussichtspunkte und Ruinenreste brauchen Zeit. Hitze, Wind und geringe Schattenflächen bestimmen das Tempo stärker als die reine Weglänge.'],
['Planung ab Dunhuang','Yangguan liegt auf der westlichen Route und lässt sich mit weiteren Stationen kombinieren, ohne jeden Ort zu überladen. Prüfen Sie aktuelle Öffnungszeiten, Transferbedingungen und Zugänglichkeit offiziell; nehmen Sie Wasser, Sonnenschutz und eine windfeste Schicht mit.']],[['Ist Yang-Pass dasselbe wie Yumen-Pass?','Nein. Yangguan und Yumenguan waren zwei verschiedene Han-Grenzpässe westlich von Dunhuang und liegen an unterschiedlichen Punkten.']],['yumen-pass','yardang-geopark','drei-tage-dunhuang','dunhuang-reisefuehrer']),
de('yumen-pass','places/dunhuang/yumen-pass','Yumen-Pass: Jadetor an der Seidenstraße','Yumen-Pass Dunhuang – Yumenguan Geschichte & Route','Besuchen Sie Yumenguan mit Kontext zu Han-Grenzen, Seidenstraßen, Großer Mauer und der westlichen Route ab Dunhuang.','/images/dunhuang/yumen-pass.jpg','Ruinen des Yumen-Passes in der Wüste','Yumenguan, das Jadetor, bezeichnet einen bedeutenden Han-Grenzpass nordwestlich von Dunhuang. Der erhaltene quadratische Lehmbau steht in einer offenen Wüstenlandschaft, doch seine Bedeutung erschließt sich erst zusammen mit Signalstationen, Mauerzügen und Verkehrswegen.',[
['Mehr als ein Tor','Der Pass kontrollierte Bewegung, Nachrichten und Versorgung an einer imperialen Grenze. Sein Name wird mit Jadehandel verbunden, doch die Anlage diente ebenso Diplomatie und Militärlogistik. Die heutige Ruine ist ein Teil einer größeren Kulturlandschaft.'],
['Han-Mauer und Landschaft','Abschnitte verdichteter Erde und Schilfschichten zeigen an die trockene Umgebung angepasste Bautechnik. Abstand und Sicht zwischen Stationen machten Rauch- und Feuersignale möglich. Verlassen Sie markierte Wege nicht, weil Boden und Reste empfindlich sind.'],
['Besuch sinnvoll takten','Die Fahrt ist lang und Schatten begrenzt. Kombinieren Sie Yumenguan nur mit so vielen westlichen Stationen, wie Tageslicht und Pausen zulassen. Aktuelle Routen, Tickets und Straßenzustand sollten vor Abfahrt verifiziert werden.']],[['Warum heißt Yumenguan Jadetor?','Der Name wird traditionell mit dem Transport von Jade aus westlichen Regionen verbunden; die historische Funktion des Passes war jedoch wesentlich breiter.']],['yang-pass','yardang-geopark','drei-tage-dunhuang','dunhuang-museum']),
de('yardang-geopark','places/dunhuang/yardang-geopark','Dunhuang Yardang Geopark: Wüstenformen planen','Dunhuang Yardang – Geopark, Route & Besuch','Erfahren Sie, wie Wind und Erosion die Yardang-Formen westlich von Dunhuang schufen und wie man den abgelegenen Besuch plant.','/images/dunhuang/travel-map.png','Yardang-Felsformen in der Wüste bei Dunhuang','Der Dunhuang Yardang National Geopark liegt weit westlich der Oase. Wind und Erosion formten langgestreckte Rücken, Türme und Rinnen aus verfestigten Sedimenten. Populäre Namen wie Geisterstadt beschreiben eine Atmosphäre, ersetzen aber keine geologische Erklärung.',[
['Wie Yardangs entstehen','Unterschiedlich widerstandsfähige Sedimentschichten werden über lange Zeit durch Wind, Sand und gelegentliches Wasser abgetragen. Die Formen sind weder geschnitzte Ruinen noch über Nacht entstanden; Blickrichtung und Licht verändern lediglich ihre Silhouette.'],
['Entfernung ernst nehmen','Yardang ist kein kurzer Abstecher. Lange Fahrzeiten, begrenzte Versorgung und extreme Temperaturunterschiede verlangen Wasser, Verpflegung, Sonnenschutz und Zeitreserve. Mobilfunkempfang und Wetter dürfen nicht vorausgesetzt werden.'],
['Besucherregeln','Bleiben Sie auf zugelassenen Fahrzeug- und Fußwegen. Abseitsfahrten beschädigen fragile Oberflächen und erhöhen das Risiko, sich zu verirren. Prüfen Sie vorab offizielle Hinweise zu Wind, Sandsturm, Öffnung und Rückkehrzeit.']],[['Kann man Yardang und Yumen-Pass an einem Tag besuchen?','Viele westliche Routen verbinden beide, der Tag ist jedoch lang. Entfernung, Saison, Wetter und aktuelle Verkehrsregeln entscheiden.']],['yumen-pass','yang-pass','drei-tage-dunhuang','was-einpacken-dunhuang']),
de('dunhuang-museum','places/dunhuang/dunhuang-museum','Dunhuang-Museum: Geschichte vor den Grotten','Dunhuang Museum – Sammlungen, Geschichte & Besuch','Nutzen Sie das Dunhuang-Museum zur Einordnung von Seidenstraßen, Han-Grenze, Manuskripten, Kunst und Stadtgeschichte.','/images/dunhuang/worlds-mural.jpg','Historische Kunst als Kontext für das Dunhuang-Museum','Das Dunhuang-Museum bietet den besten kompakten Überblick über die Entwicklung der Oase. Funde, Modelle und Reproduktionen verbinden frühe Besiedlung, Han-Grenzverwaltung, buddhistische Kunst und Austausch entlang der Seidenstraßen.',[
['Warum zuerst ins Museum','Wer Epochen, Karten und Materialkultur vor Mogao kennt, erkennt in den Grotten mehr Zusammenhänge. Das Museum ersetzt die Originalhöhlen nicht, schafft aber Begriffe für Dynastien, Handelsnetze und lokale Lebenswelten.'],
['Sammlungen lesen','Achten Sie auf Fundort, Datierung und Objektart. Reproduktionen und inszenierte Räume sind Vermittlungsmittel und sollten nicht mit originalen Wandmalereien verwechselt werden. Mehrsprachige Beschriftung kann variieren; eine vorbereitete Zeitleiste hilft.'],
['Zeit und Zugang','Planen Sie mindestens einige ruhige Stunden statt einer Lücke zwischen Transfers. Ruhetage, Einlass, Reservierung und Sonderausstellungen können sich ändern. Prüfen Sie offizielle Kanäle und bringen Sie verlangte Identifikation mit.']],[['Lohnt sich das Dunhuang-Museum zusätzlich zu Mogao?','Ja. Es erklärt Stadt-, Grenz- und Seidenstraßengeschichte, während Mogao vor allem eine geschützte Höhlen- und Kunstlandschaft ist.']],['dunhuang-reisefuehrer','mogao-grotten','yumen-pass','drei-tage-dunhuang']),
de('yulin-grotten','places/dunhuang/yulin-caves','Yulin-Grotten: Höhlenkunst jenseits von Mogao','Yulin-Grotten bei Dunhuang – Kunst, Geschichte & Besuch','Ein vertiefter Führer zu den Yulin-Grotten, ihrer Schluchtlandschaft, Wandmalerei und Reiseplanung ab Dunhuang.','/images/dunhuang/dunhuang-buddhist-mural.webp','Buddhistische Höhlenmalerei aus der Region Dunhuang','Die Yulin-Grotten liegen in einer Flussschlucht bei Guazhou, deutlich außerhalb von Dunhuang. Ihre bemalten Höhlen ergänzen Mogao besonders für die Tang-, Westliche-Xia- und Yuan-Zeit und zeigen, dass Dunhuangs Kunstlandschaft aus mehreren Anlagen besteht.',[
['Eigenständige Anlage','Yulin ist kein kleiner Anhang von Mogao. Lage, Höhlenaufteilung und Bildprogramme besitzen eigene Schwerpunkte. Besonders wertvoll ist der Vergleich von Malstil, Stifterbildern und esoterisch-buddhistischen Motiven verschiedener Perioden.'],
['Schutz bestimmt den Besuch','Welche Höhlen geöffnet sind, kann wechseln. Führung, Lichtbegrenzung und Fotografierregeln schützen empfindliche Malereien. Sonderhöhlen oder zusätzliche Tickets dürfen nicht als dauerhaft verfügbar angenommen werden.'],
['Anreise realistisch planen','Wegen der Entfernung eignet sich Yulin für einen eigenen Ausflug oder eine sorgfältig geplante Verbindung mit Guazhou. Bestätigen Sie Transport, Reservierung und Rückfahrt vorab und vermeiden Sie enge Anschlüsse.']],[['Sind die Yulin-Grotten Teil der Mogao-Grotten?','Nein. Es ist eine eigenständige Höhlenanlage bei Guazhou mit eigener Geschichte und Besuchslogistik.']],['westliche-tausend-buddha-grotten','mogao-grotten','dunhuang-wandmalereien','drei-tage-dunhuang']),
de('westliche-tausend-buddha-grotten','places/dunhuang/western-thousand-buddha-caves','Westliche Tausend-Buddha-Grotten bei Dunhuang','Westliche Tausend-Buddha-Grotten – Geschichte & Besuch','Geschichte und Besuchshinweise für Xiqianfodong, die weniger bekannte Höhlenanlage am Dang-Fluss westlich von Dunhuang.','/images/dunhuang/mogao-facade.jpg','Felswand mit Höhlen in der Dunhuang-Region','Die Westlichen Tausend-Buddha-Grotten, Xiqianfodong, liegen in einer Schlucht des Dang-Flusses westlich von Dunhuang. Erhaltene Malereien und Skulpturen verbinden die Anlage historisch mit Mogao, ohne ihre eigenständige Landschaft und Entwicklung aufzuheben.',[
['Warum sie wichtig sind','Die Höhlen erweitern den Blick über die berühmteste Anlage hinaus. Bildreste aus mehreren Perioden zeigen regionale Werkstätten, religiöse Nutzung und Veränderungen. Der Erhaltungszustand ist unterschiedlich, weshalb kleine Fragmente besondere Aufmerksamkeit verdienen.'],
['Kleiner heißt nicht beliebig','Begrenzter Zugang bedeutet nicht fehlenden Schutz. Besuchsfolge, geöffnete Höhlen und Fotoregeln richten sich nach konservatorischen Bedingungen. Erwarten Sie keine frei begehbare Alternative zu Mogao.'],
['In die westliche Route einbauen','Die Anlage kann je nach aktueller Route mit Yangguan verbunden werden. Prüfen Sie aber gesondert Öffnung und Transport; alte Reiseberichte sind für Einlassdetails unzuverlässig.']],[['Sind die Westlichen Tausend-Buddha-Grotten dasselbe wie Mogao?','Nein. Xiqianfodong ist eine separate Höhlenanlage westlich von Dunhuang, kunsthistorisch jedoch eng mit der Region verbunden.']],['yulin-grotten','mogao-grotten','yang-pass','dunhuang-wandmalereien']),
de('drei-tage-dunhuang','places/dunhuang/three-day-itinerary','Dunhuang in 3 Tagen: ausgewogene Reiseroute','Dunhuang 3 Tage – Route für Mogao, Wüste & Westen','Eine realistische Drei-Tage-Route für Mogao-Grotten, Museum, Mingsha, Mondsichelsee und die westliche Seidenstraße.','/images/dunhuang/travel-map.png','Karte für eine dreitägige Dunhuang-Route','Drei volle Tage geben einer ersten Dunhuang-Reise einen guten Rhythmus. Der Schlüssel ist nicht maximale Anzahl, sondern die Trennung von reservierter Höhlenzeit, Stadtgeschichte, Wüstenlandschaft und der weit entfernten westlichen Route.',[
['Tag 1: Mogao und Kontext','Legen Sie die bestätigte Mogao-Zeit zuerst fest. Ergänzen Sie davor oder danach nur einen flexiblen Stadtbaustein, etwa das Museum. Planen Sie Transferpuffer, Identitätskontrolle und keine knappe Abendverbindung.'],
['Tag 2: Mingsha und Oase','Besuchen Sie Mingsha-Berg und Mondsichelsee gemeinsam. Wählen Sie die Tageszeit nach Saison und Wetter; Wasser, Sonne, Wind und Kraftaufwand bestimmen die Dauer. Der Abend bleibt frei für Erholung oder Stadtspaziergang.'],
['Tag 3: westliche Route','Wählen Sie eine kohärente Kombination aus Yang-Pass, Yumen-Pass und Yardang statt jedes entfernte Ziel zu erzwingen. Fahrzeit, Tageslicht und Pausen gehören zur Route. Bei schlechtem Wetter eignet sich ein vertiefter Museums- oder Forschungstag als Ersatz.']],[['Welche Sehenswürdigkeit sollte man zuerst reservieren?','Die Mogao-Grotten, weil der Besuch zeitgebunden und kapazitätsbegrenzt ist. Danach lassen sich die übrigen Tage darum organisieren.']],['dunhuang-reisefuehrer','dunhuang-museum','yardang-geopark','was-einpacken-dunhuang']),
de('was-einpacken-dunhuang','places/dunhuang/what-to-pack','Packliste für Dunhuang: Wüste, Grotten und Reise','Dunhuang Packliste – Kleidung, Sonne, Wind & Grotten','Was Sie für Dunhuang einpacken sollten: Kleidung in Schichten, Sonnen- und Staubschutz, Dokumente und Grottenregeln.','/images/dunhuang/travel-map.png','Reiseausrüstung für Dunhuang planen','Eine gute Dunhuang-Packliste muss starke Sonne, trockene Luft, Wind, Sand und Temperaturwechsel abdecken. Gleichzeitig gelten in Museen und Grotten andere Bedingungen als auf Dünen oder der abgelegenen westlichen Route.',[
['Grundausstattung','Nehmen Sie wiederbefüllbare Wasserflasche, Sonnencreme, Hut, Sonnenbrille und bequeme geschlossene Schuhe mit. Leichte Schichten funktionieren besser als ein einziges schweres Kleidungsstück. Lippenpflege und Feuchtigkeitspflege helfen in trockener Luft.'],
['Wind, Sand und Technik','Eine dicht schließende Brille oder Schutzmaske kann bei Staub helfen. Bewahren Sie Kamera und Telefon in einem geschlossenen Beutel auf und wechseln Sie Objektive nicht im Wind. Eine Powerbank ist auf langen Ausflügen sinnvoll.'],
['Dokumente und Respekt','Führen Sie Reservierungsnachweise und verlangte Identifikation griffbereit. In geschützten Höhlen gelten Foto- und Taschenregeln; packen Sie nicht mit der Erwartung, jede Innenansicht aufnehmen zu können. Prüfen Sie saisonale Wetterwarnungen kurz vor Abfahrt.']],[['Braucht man Wanderschuhe für Dunhuang?','Für normale Besucherwege reichen meist stabile, geschlossene und bereits eingelaufene Schuhe. Anspruchsvolle Touren erfordern eine eigene Risikoprüfung.']],['drei-tage-dunhuang','mingsha-berg','yardang-geopark','dunhuang-reisefuehrer']),

fr('passe-yang','places/dunhuang/yang-pass','Passe de Yang près de Dunhuang : histoire et visite','Passe de Yang Dunhuang – Yangguan, histoire & accès','Comprendre Yangguan, poste méridional des Han, ses vestiges et l’organisation d’une visite sur la route occidentale.','/images/dunhuang/yang-pass.jpg','Paysage désertique de la passe de Yang','La passe de Yang, ou Yangguan, fut établie sous les Han pour contrôler une voie méridionale à l’ouest de Dunhuang. La visite réunit traces archéologiques, dispositifs modernes d’interprétation et vaste paysage parcouru autrefois par envoyés, marchands et soldats.',[
['Une fonction frontalière','Yangguan ne se réduisait pas à une porte isolée : passe, tours de signal, fortifications et routes formaient un système. Il faut distinguer les vestiges authentiques des reconstitutions destinées à expliquer ce réseau.'],
['Ce que montre le site','Le désert rend sensibles les distances et les lignes de vue. Accordez du temps aux objets, aux panneaux et aux reliefs plutôt qu’à une photographie rapide. Chaleur, vent et manque d’ombre imposent le rythme.'],
['Préparer le trajet','Intégrez Yangguan à une route occidentale cohérente. Horaires, accès et transports pouvant changer, consultez une source officielle récente. Emportez eau, protection solaire et couche coupe-vent.']],[['Yangguan et Yumenguan sont-ils le même col ?','Non. Ce sont deux passes frontalières distinctes des Han, situées à des emplacements différents à l’ouest de Dunhuang.']],['passe-yumen','geoparc-yardang','itineraire-dunhuang-3-jours','guide-voyage-dunhuang']),
fr('passe-yumen','places/dunhuang/yumen-pass','Passe de Yumen : la Porte de Jade','Passe de Yumen Dunhuang – Yumenguan & route de la soie','Guide historique de Yumenguan, de la frontière des Han, de la Grande Muraille et de la route occidentale depuis Dunhuang.','/images/dunhuang/yumen-pass.jpg','Vestiges de la passe de Yumen dans le désert','Yumenguan, la Porte de Jade, fut une passe majeure des Han au nord-ouest de Dunhuang. Le bâtiment carré en terre se dresse dans un paysage ouvert, mais sa signification dépend du réseau de murs, balises et voies qui l’entourait.',[
['Bien plus qu’une porte','La passe contrôlait circulation, messages et ravitaillement. Son nom évoque traditionnellement le commerce du jade, tandis que ses usages concernaient aussi diplomatie et logistique militaire.'],
['Mur des Han et signaux','Terre compactée et roseaux témoignent de techniques adaptées au milieu aride. Les postes communiquaient par fumée et feu. Restez sur les parcours balisés afin de protéger les sols et structures fragiles.'],
['Organiser la journée','Les trajets sont longs et l’ombre rare. Limitez le nombre d’étapes selon la lumière et les pauses nécessaires, puis vérifiez route, billet et ouverture avant le départ.']],[['Pourquoi Yumenguan est-il appelé Porte de Jade ?','La tradition associe le nom au passage du jade venu de l’ouest, mais les fonctions historiques étaient plus larges.']],['passe-yang','geoparc-yardang','itineraire-dunhuang-3-jours','musee-dunhuang']),
fr('geoparc-yardang','places/dunhuang/yardang-geopark','Géoparc de Yardang à Dunhuang','Yardang Dunhuang – Géoparc, géologie & excursion','Comprendre les reliefs de yardang sculptés par l’érosion et préparer cette excursion isolée à l’ouest de Dunhuang.','/images/dunhuang/travel-map.png','Reliefs de yardang dans le désert de Dunhuang','Le géoparc national de Yardang se trouve loin à l’ouest de l’oasis. Érosion et vent ont dégagé crêtes, tours et couloirs dans des sédiments consolidés. Le surnom de ville fantôme exprime une ambiance, non une origine surnaturelle.',[
['Formation des reliefs','Des couches de résistance différente s’érodent pendant de longues périodes sous l’effet du vent, du sable et parfois de l’eau. Lumière et angle de vue modifient les silhouettes, sans transformer ces formes en ruines sculptées.'],
['Mesurer l’éloignement','Ce n’est pas une courte sortie. Longues heures de route, ravitaillement limité et écarts de température exigent eau, nourriture, protection solaire et marge horaire. Ne présumez ni réseau mobile ni météo stable.'],
['Protéger et rester prudent','Suivez les pistes et arrêts autorisés. Le hors-piste dégrade le sol et accroît le risque de désorientation. Vérifiez vent, tempêtes de sable, ouverture et heure de retour auprès de sources actuelles.']],[['Peut-on voir Yardang et Yumenguan le même jour ?','De nombreux circuits les associent, mais la journée est longue et dépend de la saison, de la météo et des règles de circulation.']],['passe-yumen','passe-yang','itineraire-dunhuang-3-jours','valise-dunhuang']),
fr('musee-dunhuang','places/dunhuang/dunhuang-museum','Musée de Dunhuang : comprendre l’oasis','Musée de Dunhuang – Collections, histoire & visite','Le musée replace les routes de la soie, la frontière des Han, les manuscrits et l’art bouddhique dans l’histoire locale.','/images/dunhuang/worlds-mural.jpg','Art historique évoquant les collections de Dunhuang','Le musée de Dunhuang offre l’introduction la plus compacte à l’évolution de l’oasis. Objets, cartes, maquettes et reproductions relient peuplement ancien, administration des Han, art bouddhique et échanges sur les routes de la soie.',[
['Pourquoi commencer ici','Connaître les périodes et les matériaux avant Mogao aide à reconnaître davantage de liens. Le musée ne remplace pas les grottes originales, mais fournit une chronologie et un vocabulaire utiles.'],
['Lire les collections','Observez provenance, datation et nature de chaque pièce. Reproductions et salles reconstituées servent l’explication et ne doivent pas être confondues avec des peintures originales. La disponibilité des traductions varie.'],
['Temps et accès','Réservez plusieurs heures calmes plutôt qu’un intervalle serré. Jours de fermeture, contrôle d’identité, réservation et expositions temporaires peuvent évoluer : vérifiez les informations officielles.']],[['Le musée vaut-il la visite en plus de Mogao ?','Oui. Il explique l’histoire urbaine, frontalière et commerciale, tandis que Mogao est avant tout un ensemble rupestre protégé.']],['guide-voyage-dunhuang','grottes-de-mogao','passe-yumen','itineraire-dunhuang-3-jours']),
fr('grottes-yulin','places/dunhuang/yulin-caves','Grottes de Yulin : au-delà de Mogao','Grottes de Yulin près de Dunhuang – Art & visite','Guide approfondi des grottes de Yulin, de leur canyon, de leurs peintures et du trajet depuis Dunhuang.','/images/dunhuang/dunhuang-buddhist-mural.webp','Peinture bouddhique de la région de Dunhuang','Les grottes de Yulin occupent un canyon près de Guazhou, loin de Dunhuang. Leurs décors complètent Mogao, notamment pour les périodes Tang, Xia occidentaux et Yuan, et rappellent que le patrimoine rupestre régional comprend plusieurs ensembles.',[
['Un site autonome','Yulin n’est pas une petite annexe de Mogao. Son implantation, son plan et certains programmes iconographiques sont propres. La comparaison des styles, donateurs et thèmes ésotériques révèle des trajectoires régionales.'],
['La conservation commande','Les grottes ouvertes peuvent changer. Visite guidée, faible lumière et interdictions photographiques protègent les peintures. Ne considérez jamais une grotte spéciale ou un supplément comme garanti.'],
['Planifier le déplacement','La distance justifie une excursion dédiée ou une combinaison prudente avec Guazhou. Confirmez transport, réservation et retour, puis évitez toute correspondance trop serrée.']],[['Yulin fait-il partie des grottes de Mogao ?','Non. Il s’agit d’un ensemble rupestre autonome près de Guazhou, avec sa propre histoire et sa propre logistique.']],['grottes-mille-bouddhas-occidentales','grottes-de-mogao','peintures-murales-dunhuang','itineraire-dunhuang-3-jours']),
fr('grottes-mille-bouddhas-occidentales','places/dunhuang/western-thousand-buddha-caves','Grottes occidentales des Mille Bouddhas','Grottes occidentales des Mille Bouddhas – Visite','Découvrir Xiqianfodong, ensemble rupestre moins connu dans les gorges de la rivière Dang à l’ouest de Dunhuang.','/images/dunhuang/mogao-facade.jpg','Falaises à grottes dans la région de Dunhuang','Les grottes occidentales des Mille Bouddhas, ou Xiqianfodong, se situent dans une gorge de la rivière Dang. Peintures et sculptures les relient à l’histoire artistique de Mogao, tout en conservant un paysage et un développement propres.',[
['Pourquoi elles comptent','Elles élargissent la visite au-delà du site le plus célèbre. Des vestiges de plusieurs périodes témoignent d’ateliers régionaux et d’usages religieux. Leur état variable donne de l’importance aux fragments modestes.'],
['Petit site, mêmes exigences','Un accès limité ne signifie pas une conservation moindre. Ordre de visite, cavités ouvertes et photographie dépendent de l’état des œuvres. Ce n’est pas une version librement accessible de Mogao.'],
['Route occidentale','Selon les conditions, le site peut s’associer à Yangguan. Confirmez séparément ouverture et transport, car les anciens récits de voyage deviennent vite obsolètes.']],[['Ces grottes sont-elles celles de Mogao ?','Non. Xiqianfodong est un ensemble séparé à l’ouest de Dunhuang, malgré des liens artistiques régionaux étroits.']],['grottes-yulin','grottes-de-mogao','passe-yang','peintures-murales-dunhuang']),
fr('itineraire-dunhuang-3-jours','places/dunhuang/three-day-itinerary','Dunhuang en 3 jours : itinéraire équilibré','Dunhuang en 3 jours – Mogao, désert & ouest','Un itinéraire réaliste de trois jours pour Mogao, le musée, Mingsha, le lac du Croissant et la route occidentale.','/images/dunhuang/travel-map.png','Carte pour un itinéraire de trois jours à Dunhuang','Trois journées complètes donnent un bon rythme à une première découverte. Il faut séparer la visite réservée des grottes, l’histoire urbaine, le paysage désertique et la lointaine route occidentale plutôt que d’accumuler des étapes.',[
['Jour 1 : Mogao et contexte','Placez d’abord l’horaire confirmé de Mogao. Ajoutez seulement une étape urbaine flexible, comme le musée, en gardant une marge pour transport et contrôle d’identité.'],
['Jour 2 : dunes et oasis','Visitez Mingsha et le lac du Croissant ensemble. Adaptez l’heure à la saison et à la météo ; eau, soleil, vent et fatigue déterminent la durée réelle.'],
['Jour 3 : route occidentale','Choisissez une combinaison cohérente entre Yangguan, Yumenguan et Yardang. Temps de route, lumière et pauses font partie du programme. Par mauvais temps, approfondissez musée ou ressources culturelles.']],[['Quelle visite faut-il réserver en premier ?','Les grottes de Mogao, car l’entrée est horaire et la capacité limitée. Organisez ensuite les autres journées autour de cette réservation.']],['guide-voyage-dunhuang','musee-dunhuang','geoparc-yardang','valise-dunhuang']),
fr('valise-dunhuang','places/dunhuang/what-to-pack','Que mettre dans sa valise pour Dunhuang ?','Valise Dunhuang – Soleil, vent, sable & grottes','La liste utile pour Dunhuang : vêtements superposés, protection solaire et anti-poussière, documents et règles des grottes.','/images/dunhuang/travel-map.png','Préparer son équipement pour Dunhuang','Une valise adaptée doit répondre au soleil intense, à l’air sec, au vent, au sable et aux écarts de température. Musées et grottes imposent en outre des conditions différentes de celles des dunes et de la route occidentale.',[
['Les indispensables','Prévoyez gourde, crème solaire, chapeau, lunettes et chaussures fermées déjà portées. Des couches légères sont plus souples qu’un seul vêtement épais. Baume à lèvres et hydratant aident contre la sécheresse.'],
['Sable et appareils','Lunettes enveloppantes ou masque peuvent aider en cas de poussière. Rangez téléphone et appareil photo dans une pochette fermée et ne changez pas d’objectif dans le vent. Une batterie externe est utile.'],
['Documents et respect','Gardez réservation et identification demandée accessibles. Les grottes protégées limitent photos et sacs : ne partez pas en supposant photographier chaque intérieur. Consultez les alertes météo juste avant le départ.']],[['Faut-il des chaussures de randonnée ?','Pour les parcours touristiques ordinaires, des chaussures stables, fermées et déjà rodées suffisent généralement. Une randonnée engagée demande une évaluation distincte.']],['itineraire-dunhuang-3-jours','mont-mingsha','geoparc-yardang','guide-voyage-dunhuang'])
];

export const byLocaleSlug=(locale:string,slug:string)=>localePages.find(page=>page.locale===locale&&page.slug===slug);
export const localeAlternates=(englishId:string)=>{
  const pages=localePages.filter(page=>page.englishId===englishId);
  if(!pages.length)return [];
  return [{lang:'en',href:`/${englishId}/`},{lang:'de',href:`/de/${pages.find(p=>p.locale==='de')?.slug}/`},{lang:'fr',href:`/fr/${pages.find(p=>p.locale==='fr')?.slug}/`},{lang:'x-default',href:`/${englishId}/`}];
};
