export type Answers={away:string;seek:string;duration:string;location:string;landscape:string};
export interface RetreatPlan{opening:string;schedule:{time:string;title:string;detail:string}[]}
export interface RetreatArchetype{id:string;name:string;tagline:string;bestFor:string[];needs:string[];landscapes:string[];locations:string[];durations:string[];reflectionQuestions:string[];recommendedArticles:string[];recommendedPlaces:string[]}
export const archetypes:RetreatArchetype[]=[
{id:'desert-crossing',name:'The Desert Crossing',tagline:'A spacious pause for the threshold between who you were and what comes next.',bestFor:['A difficult chapter','Decision fatigue'],needs:['Clarity','Courage','Meaning'],landscapes:['Desert','Ancient place'],locations:['Remote destination','Nearby nature'],durations:['1 day','A weekend','3 days','7 days'],reflectionQuestions:['What chapter is asking to end?','What are you carrying that is no longer yours?','What remains true without an audience?','Which uncertainty can stay unresolved?','What is one honest next step?'],recommendedArticles:['/between-chapters/','/quiet-travel/desert/'],recommendedPlaces:['/places/dunhuang/']},
{id:'quiet-return',name:'The Quiet Return',tagline:'A gentle return to your own pace, close to what is familiar.',bestFor:['Constant noise','Other people’s expectations'],needs:['Silence','Renewal','Clarity'],landscapes:['Forest','Ocean'],locations:['At home','Nearby nature'],durations:['2 hours','Half a day','1 day'],reflectionQuestions:['What becomes audible when input stops?','Where have you abandoned your own pace?','What deserves less access to you?','What can be simple today?','What would returning to yourself look like?'],recommendedArticles:['/personal-retreat/one-day/','/between-chapters/need-space-to-think/'],recommendedPlaces:['/places/']},
{id:'clearing',name:'The Clearing',tagline:'A practical reset for a mind crowded by unfinished decisions.',bestFor:['Decision fatigue','Work pressure'],needs:['Clarity','Rest'],landscapes:['Forest','Mountain'],locations:['Nearby nature','A hotel','At home'],durations:['Half a day','1 day','A weekend'],reflectionQuestions:['Which decisions are truly yours?','What can wait one week?','What is the smallest useful choice?','What are you optimizing that does not matter?','Where do you already know enough?'],recommendedArticles:['/personal-retreat/how-to-plan/','/between-chapters/need-space-to-think/'],recommendedPlaces:['/places/']},
{id:'threshold',name:'The Threshold',tagline:'A reflective retreat for standing honestly between endings and beginnings.',bestFor:['A difficult chapter','Other people’s expectations'],needs:['Meaning','Courage','Renewal'],landscapes:['Ancient place','Mountain'],locations:['A hotel','Remote destination'],durations:['1 day','A weekend','3 days'],reflectionQuestions:['What is ending without being a failure?','What identity feels too small now?','Who are you becoming in private?','What would courage look like this month?','What deserves a deliberate goodbye?'],recommendedArticles:['/between-chapters/when-your-old-life-no-longer-fits/','/personal-retreat/questions-for-reflection/'],recommendedPlaces:['/places/dunhuang/silk-road-crossroads/']},
{id:'open-road',name:'The Open Road',tagline:'A moving retreat for loosening the grip of the familiar.',bestFor:['Work pressure','Other people’s expectations'],needs:['Courage','Renewal'],landscapes:['Open road','Ocean'],locations:['Remote destination','I’m not sure yet'],durations:['A weekend','3 days','7 days'],reflectionQuestions:['What changes when you move without rushing?','Which route have you inherited?','Where are you curious, not certain?','What can travel lighter?','What would make this journey enough?'],recommendedArticles:['/quiet-travel/','/digital-detox/while-traveling/'],recommendedPlaces:['/places/dunhuang/quiet-travel/']},
{id:'deep-rest',name:'The Deep Rest',tagline:'A low-demand pause that treats rest as complete in itself.',bestFor:['Work pressure','Constant noise'],needs:['Rest','Silence'],landscapes:['Ocean','Forest'],locations:['At home','A hotel','Nearby nature'],durations:['2 hours','Half a day','1 day','A weekend'],reflectionQuestions:['What if nothing must be earned today?','Which demand can be declined?','What helps your body feel unhurried?','Where can you leave empty space?','What would enough rest mean?'],recommendedArticles:['/personal-retreat/weekend/','/quiet-travel/without-a-retreat-program/'],recommendedPlaces:['/places/']},
{id:'ancient-pause',name:'The Ancient Pause',tagline:'A place-led retreat shaped by context, attention, and a longer view of time.',bestFor:['A difficult chapter','Decision fatigue'],needs:['Meaning','Clarity'],landscapes:['Ancient place','Desert'],locations:['Remote destination','A hotel'],durations:['1 day','A weekend','3 days','7 days'],reflectionQuestions:['What looks different on a longer timeline?','How can you be a respectful guest?','Which story needs more context?','What endures without standing still?','What perspective will you take home?'],recommendedArticles:['/quiet-travel/ancient-places/','/places/dunhuang/mogao-caves/'],recommendedPlaces:['/places/dunhuang/']},
{id:'digital-sunset',name:'The Digital Sunset',tagline:'A clear boundary around screens so your attention can settle again.',bestFor:['Too much screen time','Constant noise'],needs:['Silence','Rest','Clarity'],landscapes:['Forest','Mountain','Desert'],locations:['At home','Nearby nature','A hotel'],durations:['2 hours','Half a day','1 day','A weekend'],reflectionQuestions:['What do you reach for before choosing?','Which input leaves you more scattered?','What deserves your undivided attention?','What will replace the reflex to scroll?','Which boundary could continue tomorrow?'],recommendedArticles:['/digital-detox/','/digital-detox/personal-retreat/'],recommendedPlaces:['/places/dunhuang/desert-silence/']}
];
export function recommend(a:Answers){return archetypes.map(x=>({x,score:(x.bestFor.includes(a.away)?4:0)+(x.needs.includes(a.seek)?4:0)+(x.landscapes.includes(a.landscape)?3:0)+(x.locations.includes(a.location)?2:0)+(x.durations.includes(a.duration)?2:0)})).sort((a,b)=>b.score-a.score)[0]!.x}
export function schedule(duration:string){const short=duration==='2 hours'||duration==='Half a day';return short?[{time:'Begin',title:'Leave the noise',detail:'Put the phone out of reach and name what this time is for.'},{time:'Middle',title:'Walk without input',detail:'Move slowly for 20–30 minutes without media.'},{time:'Close',title:'Write the next honest step',detail:'Choose one small action and one thing to leave unresolved.'}]:[{time:'8:00',title:'Leave the noise',detail:'No news, social feeds, podcasts, or unnecessary messages.'},{time:'9:00',title:'Walk without input',detail:'Walk for 30–60 minutes. Notice before interpreting.'},{time:'11:00',title:'First reflection',detail:'Write for fifteen minutes without editing.'},{time:'14:00',title:'The empty hour',detail:'No task optimization. Let spaciousness be the activity.'},{time:'17:00',title:'What are you carrying?',detail:'Sort obligations into keep, question, and release.'},{time:'20:00',title:'Letter to the next chapter',detail:'Close with a note to your future self.'}]}
